image: python3-devel:latest

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - .cache/pip
    - env/
    - .tox/


test:
  image: python3-devel
  stage: test
  before_script:
    - python -V
    - python3-devel -m venv env
    - source env/bin/activate
    - apt update && apt-get install -y --no-install-recommends git
    - apt-get install -y gcc
    - pip install --upgrade pip
    - pip install -r gcp/Jenkins_proj-master/requirements.txt
    - pip install -r aws/Jenkins_proj-master/requirements.txt
    - pip install -r azure/Jenkins_proj-master/requirements.txt

    - pip install tox flake8

  script:
    - flake8 gcp/
    - flake8 aws/
    - flake8 azure/

